all:
  children:
    OSEv3:
      vars:
        ansible_ssh_user: root
        ansible_user: root
        debug_level: 2
        internal_console_port: 8443
        openshift_deployment_type: origin
        openshift_disable_check: docker_storage,memory_availability,disk_availability
        openshift_master_api_port: 8443
        openshift_master_cluster_hostname: console.okd3-prod.seems.local
        openshift_master_cluster_public_hostname: console.okd3-prod.seems.local
        openshift_master_console_port: 8443
        openshift_master_default_subdomain: apps.okd3-prod.seems.local
        openshift_master_htpasswd_file: /etc/origin/master/htpasswd
        openshift_master_htpasswd_users:
          okdadmin: $apr1$XbI1zlV3$FuiA0g8tUfbYmZDeZpyRs/
          okdadmin1: $apr1$XbI1zlV3$FuiA0g8tUfbYmZDeZpyRs/
        openshift_master_identity_providers:
          - challenge: 'true'
            kind: HTPasswdPasswordIdentityProvider
            login: 'true'
            name: htpasswd_auth
      children:
        etcd:
          hosts:
            okd3-master[0:2].seems.local:
              openshift_node_group_name: node-config-master
        lb:
          hosts:
            okd3-lb0.seems.local:
        masters:
          hosts:
            okd3-master[0:2].seems.local: { }
        nfs:
          hosts:
            okd3-lb0.seems.local: { }
        nodes:
          hosts:
            okd3-infra[0:1].seems.local:
              openshift_node_group_name: node-config-infra
            okd3-master[0:2].seems.local: { }
            okd3-node[0:1].seems.local:
              openshift_node_group_name: node-config-compute
