all:
  children:
    OSEv3:
      vars:
        # Debug Level
        debug_level: 2
        
        # Ansible Connection
        ansible_ssh_user: root
        ansible_user: root
        
        # Installation
        openshift_deployment_type: origin
        openshift_disable_check: docker_storage,memory_availability,disk_availability
        openshift_cluster_monitoring_operator_install: false
        
        # UI Access
        internal_console_port: 8443
        openshift_master_api_port: 8443
        openshift_master_console_port: 8443
        openshift_master_cluster_hostname: console.okd3-prod.seems.local
        openshift_master_cluster_public_hostname: console.okd3-prod.seems.local
        openshift_master_default_subdomain: apps.okd3-prod.seems.local

        # Certificates
        # openshift_redeploy_openshift_ca: true
    
        openshift_hosted_router_certificate:
          certfile: /xxx.crt.pem
          keyfile: /xxx.key.pem
          cafile: /ca.crt.pem

        openshift_named_certificates_redeploy: true
        openshift_master_named_certificates:
          - certfile: /root/leaf2.crt.pem
            keyfile: /root/leaf2.key.pem
            cafile: /root/ca.crt.pem
        
        # Initial Authentication
        openshift_master_htpasswd_file: /etc/origin/master/htpasswd
        openshift_master_htpasswd_users:
          okdadmin: $apr1$XbI1zlV3$FuiA0g8tUfbYmZDeZpyRs/
          # okdadmin:dmlAjICyfrYXCsEH3NOoeeZMBkbo9G0JJy70z4etiO1dlCoo
        openshift_master_identity_providers:
          - challenge: 'true'
            kind: HTPasswdPasswordIdentityProvider
            login: 'true'
            name: htpasswd_auth
      children:
        etcd:
          hosts:
            okd3-master[0:2].seems.local:
              openshift_node_group_name: node-config-master
        lb:
          hosts:
            okd3-lb0.seems.local:
        masters:
          hosts:
            okd3-master[0:2].seems.local: { }
        nfs:
          hosts:
            okd3-lb0.seems.local: { }
        nodes:
          hosts:
            okd3-infra[0:1].seems.local:
              openshift_node_group_name: node-config-infra
            okd3-master[0:2].seems.local: { }
            okd3-node[0:1].seems.local:
              openshift_node_group_name: node-config-compute
